combine_control_expr = false
condense_wildcard_suffixes = true
imports_indent = "Block"
match_block_trailing_comma = true
max_width = 80
force_multiline_blocks = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
report_todo = "Always"
struct_field_align_threshold = 16
struct_lit_single_line = false
use_try_shorthand = true
wrap_comments = true
