indent_style = "Block"
use_small_heuristics = true
binop_separator = "Front"
combine_control_expr = false
comment_width = 80
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
error_on_line_overflow = true
error_on_unformatted = true
fn_args_density = "Tall"
brace_style = "SameLineWhere"
empty_item_single_line = true
fn_single_line = false
where_single_line = false
force_explicit_abi = true
format_strings = true
hard_tabs = false
imports_indent = "Block"
imports_layout = "Mixed"
merge_imports = true
match_block_trailing_comma = true
max_width = 80
merge_derives = true
force_multiline_blocks = true
newline_style = "Unix"
normalize_comments = false
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
report_todo = "Always"
report_fixme = "Always"
skip_children = false
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 16
spaces_around_ranges = false
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
match_arm_blocks = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
unstable_features = true

ignore = [
]
