#!/usr/bin/env bash

VK_PATH=~/dev/vulkan/sdk/*/x86_64/bin/
COMPILER=$VK_PATH/glslangValidator

function compile_fast {
  name=$1; extension=$2; prefix=${name}_

  # Check for syntax errors
  if ! $COMPILER --client vulkan100 $name.$extension \
    -o out/$prefix$extension.spv
    then exit 1
  fi
}

function compile {
  name=$1; extension=$2; prefix=${name}_
  compile_fast $name $extension

  # Generate binary and disassembly
  $COMPILER -H $name.$extension \
    -o out/$prefix$extension.spv \
    > out/$prefix$extension.spvasm
}

function compile_all {
  compile $1 vert
  compile $1 frag
}

mkdir -p out

if [ "$1" = "-f" ]; then
  compile_fast base vert
  compile_fast base frag
  echo Warning: skipped remaining shaders!
  exit
fi

./clean; mkdir out
compile_all base
compile_all debug
compile_all font2d
compile_all font3d
