#!/usr/bin/env bash

VK_PATH=~/dev/vulkan/sdk/*/x86_64/bin/
COMPILER=$VK_PATH/glslangValidator

function compile {
  name=$1; extension=$2; prefix=$3
  if ! $COMPILER -H $name.$extension \
    -o out/$prefix$extension.spv \
    > out/$prefix$extension.spvasm
    then exit 1
  fi
}

./clean

compile_font3d vert
compile_font3d frag

compile_debug vert
compile_debug frag

compile shader vert
compile shader frag
