#!/usr/bin/env bash

VK_PATH=~/dev/vulkan/sdk/*/x86_64/bin/
COMPILER=$VK_PATH/glslangValidator

function compile {
  name=$1; extension=$2; prefix=${name}_

  # Check for syntax errors
  if ! $COMPILER --client vulkan100 $name.$extension \
    -o out/$prefix$extension.spv
    then exit 1
  fi

  # Generate binary and disassembly
  $COMPILER -H $name.$extension \
    -o out/$prefix$extension.spv \
    > out/$prefix$extension.spvasm
}

function compile_all {
  compile $1 vert
  compile $1 frag
}

./clean
mkdir -p out

compile_all font3d
compile_all debug
compile_all base
